{ config, pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    vscode
    vscode-extensions.ms-vscode.live-server
    live-server
    xed-editor
    kitty
    windowmaker
    dockapps.wmcube
    dockapps.AlsaMixer-app
    xfe
    discord
    virtualbox
    vlc
    plex-desktop
    prismlauncher
    spotify
    unzip
    wineWow64Packages.yabridge
    jre8
    proton-vpn
    audacity
    blender
    p7zip
    vpkedit
    r2modman
    wl-clipboard
    mako
    waybar
    obs-studio
    shotcut
    easyeffects
    kdePackages.oxygen
    python3
    putty
    decent-sampler
    uxplay
    telegram-desktop
    qbittorrent
    mumble
    git
    tmux
    wget
    fish
  ];
}
